### ISSUE TITLE
Duplicating payouts.

### ISSUE THREAD

**Issue by DavionKalhen** [dakk/lisk-pool#13]
http://risescanner.com/acnt/2149449110753305485R/

Follow the 25k Rise being passed around. Each of the 4 accounts are receiving payouts from 4 different pools on the same day. The guy's making a killing.

**Comment by dakk** [comment]
This is a pool hopping problem; I wrote a tut for mitigating the problem: https://github.com/dakk/lisk-pool#avoid-vote-hoppers
