### ISSUE TITLE
last line in payments.sh doubled

### ISSUE THREAD

**Issue by corsaro1** [dakk/lisk-pool#4]
when launching script on ARK, it writes last line in payments.sh 2 times

`sleep 3
echo Sending 16856.666512552234 to AXef14p6h6Yhr7gvhYXqx5T74ksbYFcz6n
curl -k -H  "Content-Type: application/json" -X PUT -d '{"amount": 1685666651255, "recipientId": "ADDRESS", "secret": "SECRET"}' https://xxxx/api/transactions

sleep 3
curl -k -H  "Content-Type: application/json" -X PUT -d '{"amount": 1685666651255, "recipientId": "ADDRESS", "secret": "SECRET"}' https://xxxx/api/transactions

sleep 3`

**Comment by dakk** [comment]
3d3ea6939a1e9742be69d550a4f033d866b14a84
